### ISSUE TITLE
"Longer" locale format support (en-us, en-uk, pt-br)

### ISSUE THREAD

**Issue by rslonik** [njam/nuxt-i18n-module#14]
Hello,

First, thanks for this module! I really appreciate this!

Second: I need to work with locales like this: en-us, en-uk. 

I've changed the addLangParamToRoute() regex from `\\w{2}` to `[\\w-]{2,5}`

It works, but obviously changing directly in the module code isn't the right thing to do. I thought about forking with this change, but first I'd like to know if you are interested in a PR with this feature...

**Comment by njam** [comment]
Sure that sounds very reasonable. If you could create a PR I'd be happy to merge and release it.

**Comment by njam** [comment]
Thanks! It's released as v0.0.4
