### ISSUE TITLE
Nuxt official i18n example - setting language as default

### ISSUE THREAD

**Issue by Jesus82** [njam/nuxt-i18n-module#17]
Hi, I followed the i18n example in the official documentation [https://nuxtjs.org/examples/i18n/](https://nuxtjs.org/examples/i18n/) 
and now I have added this module in top of that, in order to generate correct linking. 
In the official example, they use a "fallback" language, so whenever you don't specify the locale, the default one would be used. Also, if your fallback locale is 'en', when typing `/en/home`, it redirects to `/home`
Is there any way to reproduce this behaviour when you add this module?

Thanks!

**Comment by njam** [comment]
@Jesus82 this functionality is currently not available with this module. But such a feature would be nice!
There's a patch for such functionality being discussed in #16.

I think in such case the default/fallback route (`/foo`) should be the *only* route for the default language, and should completely replace the `/en/foo` route (if "en" is the default).
Pull request welcome!
