### ISSUE TITLE
Spam console when rouute is not found

### ISSUE THREAD

**Issue by orblazer** [njam/nuxt-i18n-module#18]
Hello,
When acces to unknown route the console is spam by `[vue-router] relative params navigation requires a current route.`
This is caused by this line : https://github.com/njam/nuxt-i18n-module/blob/fc64a47acb69f21d46dbed25517bba8064c9676d/src/templates/plugin.js#L83

thanks.

**Comment by njam** [comment]
I can't reproduce this.
Are you using nuxt as a server, or are you generating static pages?
What is your nuxt version?
Can you share a reproducable example?

**Comment by orblazer** [comment]
I have the last version of Nuxt and i not generate static pages (because i don't know hox i can make an JAMStack from that).

My config of nuxt-18n (with my PR for v0.0.5) :
```
['nuxt-i18n-module', {
  languages: ['fr', 'en'],
  defaultLanguage: 'fr',
  edirectDefaultLang: false
}]
```

The all routes is generate dynamicly.

Note: After debugging i have found is caused because the link could not resolve language path the generated links: 
![image](https://user-images.githubusercontent.com/1344792/42538622-b0325c00-8498-11e8-8513-fbbddfba108e.png)

Edit : This is poduced when path is getter then 5 letters, path like that : `/ddssaa`

**Comment by njam** [comment]
I can still not reproduce this. I was running current master, and serving the website with "nuxt build".
I'm loading the URL `/ddssaa` either through the address bar, or through a nuxt link.

Please provide a simple reproducible setup (preferably code), and step-by-step instructions how to reproduce this issue, if you want me to investigate this further.
