### ISSUE TITLE
Language attribute on html not updating 

### ISSUE THREAD

**Issue by stophecom** [njam/nuxt-i18n-module#30]
Happens with Nuxt 2.0. (Release notes: https://nuxtjs.org/guide/release-notes/)  E.g. `lang=en` on `<html/>` doesn't update according to the language anymore.

**Comment by njam** [comment]
I can't see any `lang` attribute on the `<html>` element at all, neither with Nuxt version 1.4 nor with 2.1.

Not on the DOM:
![image](https://user-images.githubusercontent.com/360800/46573299-98754d80-c993-11e8-89eb-11599ae06cef.png)

Not in the source code:
![image](https://user-images.githubusercontent.com/360800/46573304-a5923c80-c993-11e8-823d-49f498385358.png)

What am I missing?

BTW I've updated the dependency on Nuxt to version 2 in #31, which seems to work fine.

**Comment by stophecom** [comment]
Oh didn't realise my problem is not related to the module :) Will close

> BTW I've updated the dependency on Nuxt to version 2 in #31, which seems to work fine.

yiipiee
