### ISSUE TITLE
Use absolute path for `hreflang` attribute

### ISSUE THREAD

**Issue by stophecom** [njam/nuxt-i18n-module#41]
Google seems to recommend absolute links for alternative language links: https://support.google.com/webmasters/answer/189077?hl=en

E.g. `<link rel="alternate" hreflang="en-gb"
        href="http://en-gb.example.com/page.html" />`

Should be able to fix here: https://github.com/njam/nuxt-i18n-module/blob/e025a732377ee0d38b134775034b857510d0ca62/src/templates/plugin.js

**Comment by njam** [comment]
We're using VueRouter to resolve _hreflang_ URLs. There's a [`base`](https://router.vuejs.org/api/#base) option, but unfortunately it doesn't work with absolute URLs. Opened a ticket about it: https://github.com/vuejs/vue-router/issues/2927

**Comment by njam** [comment]
Unfortunately absolute URLs are out of scope for VueRouter, so we'll need to handle it here. I will look into it.

**Comment by njam** [comment]
New option `rootUrl` is available in version 0.3.0
