### ISSUE TITLE
Should switching language remove trailing slash?

### ISSUE THREAD

**Issue by njam** [njam/nuxt-i18n-module#7]
@christopheschwyzer wrote:
> When I switch the language, the trailing slash gets removed. Seems to be intended, but not sure about it. (Causing issue with dynamic loaded content)

@christopheschwyzer so usually routes in Nuxt.js have trailing slashes?
Like `example.com/` and `example.com/foo/`?

**Comment by stophecom** [comment]
Actually, no. Only when reloading (on generated routes). So if you are on `example.com/foo` and you reload the url will be `example.com/foo/`. I assume it's because it uses the `index.html` inside the `foo` folder like `/foo/index.html`. So it's unrelated to this module. I will close it.
