### ISSUE TITLE
steps mentions is not correct

### ISSUE THREAD

**Issue by sudhir600** [njam/nuxt-i18n-module#8]
You have not mention installation and used process step by step.

i have seen lot of code in middleware too but you didn't mention anything.
I follow your step but i am getting error -_vm.$ not a function.

**Comment by njam** [comment]
Yes, some documentation should be added!
@christopheschwyzer maybe you  want to help out here? I've just published the code to NPM, so it should be easier to install it.

**Comment by njam** [comment]
The module is now published on NPM, and installation instructions are in the README:
https://github.com/njam/nuxt-i18n-module#installation--configuration
